### ISSUE TITLE
api oauth docs missing

### ISSUE THREAD

**Issue by joernhees** [mattermost/docs#103]
so we're trying to write a mattermost chat-bot that doesn't have the limitations of the web-hooks (no private channels for example)... We thought this should be easy enough by making a full user-account for the bot and logging it in via the API...

sadly we use our gitlab's oauth and the following section is empty so we can't get it to work:
http://docs.mattermost.com/developer/web-service.html#oauth2

would be cool if someone could take the time to add that section...

by guessing (not sure it's the right track) we already could acquire an `access_token` from the gitlab oauth:

```python
client_id = 'the one of mattermost in our gitlab'
r = requests.post(
    'https://git.example/oauth/token',
    data={
        "grant_type": "password",
        "username": user,
        "password": pw,
        "client_id": client_id,
    }
)
access_token = r.json()['access_token']
```

but using it only results in a 401:
```python
ri = requests.get(
    'https://chat.example/api/v1/users/me',
    headers={'Authorization': 'Bearer ' + access_token}
)

ri.status_code, ri.json()
(401,
 {u'detailed_error': u'token=...xxx...',
  u'id': u'api.context.session_expired.app_error',
  u'is_oauth': False,
  u'message': u'Invalid or expired session, please login again.',
  u'request_id': u'...yyy...',
  u'status_code': 401})
```

**Comment by joernhees** [comment]
found a hackish solution myself, but still would be interested in one which doesn't involve mimicking a browser and parsing gitlab's html for csrf tokens...

http://stackoverflow.com/a/36652283/1423333

**Comment by it33** [comment]
Hi @joernhees, the approach you're attempting isn't supported because a pop-up is required for the OAuth process to complete. Another approach would be to approximate an app-password account by creating an email auth account, setting it up with a large password, and using the APIs to log in. 

The longer term solution for this is some sort of bot user. Could we ask your help to [upvote](https://mattermost.uservoice.com/forums/306457-general/suggestions/12280503-bot-users), [suggest new features](http://www.mattermost.org/feature-requests/) or discuss such a change on the feature idea forum? 

So the feature idea is centralized on the feature idea forum, closing this issue for now.
