### ISSUE TITLE
Add non-profit discounting FAQ

### ISSUE THREAD

**Issue by it33** [mattermost/docs#1039]
add to https://docs.mattermost.com/overview/faq.html#business-questions

#### Why does Mattermost discount to certain kinds of non-profits and not others? My non-profit qualifies for non-profit discounts provided by other software companies. 

While we welcome anyone use the open source version of Mattermost Team Edition free of charge, Mattermost, Inc., like any software company, has specific discounting programs for its commercial Mattermost Enterprise Edition based on commercial objectives. Objectives of the discounting programs include the suitability of potential case studies, references, word-of-mouth promotion as well as public promotion of solutions, among many other factors. 

Learn more about our non-profit discount program at https://about.mattermost.com/mattermost-mondays/

**Comment by it33** [comment]
@JeffSchering not urgent, have your help adding this? 

For tickets ready to go, and not time-critical, I'll just assign to you?

**Comment by JeffSchering** [comment]
@it33 
The length of the question will prove unwieldy when it comes to using it as title in the doc and as an item in the ToC due to wrapping and cropping issues.

I propose the following text:

----
### Why does Mattermost have a discount for certain kinds of non-profits but not for others?

Although your non-profit might qualify for discounts from other software companies, Mattermost Inc. has criteria based on our own commercial objectives. The objectives of our discount program include the suitability of potential case studies, references, word-of-mouth promotion and public promotion of solutions, and many other factors.

Although you're always welcome to use the open source Team Edition of Mattermost free of charge for any purpose, we reserve the right to set a price for the Enterprise Edition that suits our commercial objectives.

Learn more about our non-profit discount program at https://about.mattermost.com/mattermost-mondays/

----

**Comment by it33** [comment]
Agree on title, propose the below: 
```
While we welcome anyone use the open source version of Mattermost Team Edition free of charge, Mattermost, Inc., like any software company, has specific discounting programs for its commercial Mattermost Enterprise Edition based on business objectives. Objectives of the discounting programs include the suitability of potential case studies, references, word-of-mouth promotion as well as public promotion of solutions, among many other factors. 

Learn more about our non-profit discount program at https://about.mattermost.com/mattermost-mondays/
```

There's a lot of nuance in this answer and we need specific wording, as one example, we don't allow people to use Team Edition for any purpose, see Configuration doc under Terms for details on "Conditions of Use".

**Comment by JeffSchering** [comment]
PR opened: [Added FAQ about discounts for non-profits #1047](https://github.com/mattermost/docs/pull/1047)
