### ISSUE TITLE
Document a bare-bones installation of Mattermost

### ISSUE THREAD

**Issue by peterdamian** [mattermost/docs#1504]
Open source projects become more widely adopted the easier they are to use. This proposed document aims to describe the simplest possible Mattermost installation. Installation will exclude the following elements:

- NGINX
- TLS
- systemd

Excluding these elements reduces possible points of failure and increases the chances of a successful installation.

The target platform should probably be Ubuntu 16.04.

After installation and configuration show how to perform tasks that will appeal to first-time users. These might include:

- How to invite a user to join a team. 
- How to connect to the server using the mobile app.
- Trigger an email by mentioning a user's name.

Since this is a test installation, removal of Mattermost files should also be documented.

**Comment by justinegeffen** [comment]
I've updated the RHEL docs to include a link to the config section. Looking through the suggestions, I feel they are addressed by the Docker content for [Prod](https://docs.mattermost.com/install/prod-docker.html) and [Local](https://docs.mattermost.com/install/docker-local-machine.html). 

@peterdamian, I agree with all your suggestions. As this issue is a couple of months old, if you have the bandwidth to let me know whether you have any feedback on the current docs and whether they're more aligned with your suggestions it would be most welcome. :)

**Comment by justinegeffen** [comment]
@dontoisme, tagging you in this as it may be relevant to onboarding/the growth spike. Closing issue.
