### ISSUE TITLE
Inline hyperlinking needs to be consistent

### ISSUE THREAD

**Issue by seenthattinker** [mattermost/docs#1581]
The inline hyperlinking needs to be edited for consistency. The following example illustrates:

Requirements and Installation Guides
Mattermost supports workplace messaging for teams using one to three servers with instructions available in the **Install Guides** section of this documentation. See Software and Hardware Requirements documentation for server sizing estimates.

The "Install Guides"  section is referenced in proper noun capitalization in the above example. It should be hyperlinked. One click drill downs are the hallmark of online documentation.

**Comment by justinegeffen** [comment]
Hi @seenthattinker. I've taken a look through our Requirements and Installation Guides and wanted to confirm whether you're referring to a specific guide or the guides in general? 

Here's [one example](https://docs.mattermost.com/install/install-ubuntu-1604.html) of a guide with hyperlinks. If you'd be open to letting me know whether this is the correct guide or, if not, providing the link/s that'd be great. 

You're also welcome to edit the docs in question and submit a pull request so that we can take a look at your changes and review them. 

Thank you!

**Comment by justinegeffen** [comment]
Hi @seenthattinker. I've reviewed the content and I'm not able to locate the exact location of the missing hyperlinks. The content or structure may have changed since this issue was opened. Please let me know if that is the case and, if so, if the issue has been resolved. :) Thank you!

**Comment by justinegeffen** [comment]
This has been addressed by docs 2.0. Closing. :)
