### ISSUE TITLE
Message separator style

### ISSUE THREAD

**Issue by landkommunenhippie** [mattermost/docs#2078]
Hello Mattermost team,

First of all thank you for this nice chat tool.
Something I would really appreciate is a theme-style that makes it possible to create message separators. A border Style or something similiar would be enough for us.

Thank you and kind regards,
Tobias

**Comment by amyblais** [comment]
Hi @landkommunenhippie! Thank you for reaching out.

Here are some docs that might help:

- https://docs.mattermost.com/deployment/customize-mattermost.html
- https://docs.mattermost.com/help/settings/account-settings.html#theme
-https://docs.mattermost.com/help/settings/theme-colors.html

Let me know if that helps!

**Comment by amyblais** [comment]
Hi @landkommunenhippie, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
