### ISSUE TITLE
Server URL/Cannot connect to Server

### ISSUE THREAD

**Issue by Sparky135** [mattermost/docs#2106]
Hi, 

I am trying to create a server but it says the server isn't connecting. I created a URL but it still does not connect. How can I fix this?

![screenshot 13 _li](https://user-images.githubusercontent.com/40370659/41560486-70a3ffbc-7304-11e8-9d0c-f69c316dacc6.jpg)

**Comment by amyblais** [comment]
Hi @Sparky135! Thank you for reaching out.

This is the docs repo, can you help open a new issue either in the [server repo](https://github.com/mattermost/mattermost-server/issues), [mobile app repo](https://github.com/mattermost/mattermost-mobile/issues) or the [Peer-to-peer Forum](https://forum.mattermost.org/). When you do so, please include any relevant information [from this page](https://docs.mattermost.com/process/support.html) so that we can diagnose the issue.

**Comment by amyblais** [comment]
Hi @Sparky135, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
