### ISSUE TITLE
Update Zoom plugin instructions

### ISSUE THREAD

**Issue by icelander** [mattermost/docs#2474]
Zoom has made changes in how they create webhooks, so the [Zoom plugin guide](https://docs.mattermost.com/integrations/zoom.html) needs updated.

From Zoom support: 

> The username and password fields are for webhook apps setup using the V1 webhook. The new marketplace webhooks don't have that option. You can recreate the webhook using the marketplace to circumvent entering the credentials into those fields.

**Comment by svelle** [comment]
I'd suggest waiting till Feb 11th, because then Zoom will deprecate the old developer portal and move to the new site. 
After that new screenshots can be made for the docs because right now the dev portal is full of deprecation warnings and in the set up process you're switching between old and new site all the time.

**Comment by svelle** [comment]
This can be closed now I guess. @amyblais @jasonblais
