### ISSUE TITLE
"online" is not recognised as a word by either English dictionary

### ISSUE THREAD

**Issue by rusty595** [mattermost/docs#2535]
![image](https://user-images.githubusercontent.com/10696825/53162972-075ee600-35c5-11e9-9e0f-fc508050592a.png)
![image](https://user-images.githubusercontent.com/10696825/53163002-15146b80-35c5-11e9-9cd7-c1a126f9cc5b.png)

I'm using the Windows version 4.2.0 and every time I type "online" in Mattermost it gets a red squiggly line.

**Comment by svelle** [comment]
Hey @rusty595 is this happening in the desktop version of Mattermost?
There's currently not a custom dictionary used in the desktop app but I've already opened up a [PR](https://github.com/jfmdev/simple-spellchecker/pull/22) to get this fixed in the spellchecker module that's used inside the desktop app.

**Comment by rusty595** [comment]
Yes, this is in the Windows Desktop version. Thanks for the PR.

**Comment by svelle** [comment]
PR is merged, I'll look into updating the package in the Desktop client ;)

**Comment by svelle** [comment]
It's fixed now this can be closed @jasonblais @amyblais

**Comment by jasonblais** [comment]
Thanks !
