### ISSUE TITLE
Template for Product Recipes

### ISSUE THREAD

**Issue by wiersgallak** [mattermost/docs#2718]
Create a template for writing product recipes.  
Consider (not an exhaustive list):  
 - Problem to be solved by recipe
 - Pre-installation/pre-configuration notes
 - How to instructions to set up and configure the solution
 - categorization of recipe amongst others for easy search and retrieval.

**Comment by ABresting** [comment]
Hi @wiersgallak 
I want to contribute to the Product recipes project. As a developer and researcher, I will do both PoC and generalizing the process involved in the form of a blog.

I want to approach this by first discussing the possible templates. I believe there exists a template like the following:
https://mattermost.com/blog/mattermost-recipe-how-to-create-a-chatbot-with-dialogflow-and-google-cloud-functions/

This looks fine, few additions might help such as the left side space is empty which could be used for a blog index since it's been primarily divided into 3 sections at present. Tags can be added to the blogs to find similar articles, soft of a hashtag #hashtag . Such ideas can lay the foundation of a fresh template to improve the UX.

**Comment by justinegeffen** [comment]
This has been solved by: https://handbook.mattermost.com/operations/messaging-and-math/how-to-guides-for-m-and-m/how-to-write-mattermost-recipes#mattermost-recipes. I've added some additional content to that page.
