### ISSUE TITLE
Request for Documentation: Does the sysadmin get any notification when the data retention period is changed.

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3131]
Mattermost user `george` from https://community-daily.mattermost.com has requested the following be documented:

```
Does the sysadmin get any notification when the data retention period is changed?

No, the new config is updated, but the sysadmin does *not* receive any feedback on what the effects will be (e.g. reporting of how many messages to be deleted).
```

See the original post [here](https://community-daily.mattermost.com/_redirect/pl/bueh65hs83fg7f9bezdxcomuke).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by bvineyar** [comment]
Can I take this one?

**Comment by wiersgallak** [comment]
Some additional content from the discussion in channel: 

Data retention runs the actual deletion query in batches. It deletes data in blocks of 1,000 records per query in order to not lock-up the database for extended periods of time with slow, long-running queries (keeping to this limit keeps the query down to a few milliseconds execution time on the database itself). Each batch of data is deleted based on indexes, so the queries are generally quite quick to execute on such small batches meaning the server will stay fully responsive while the process is running.

**Comment by justinegeffen** [comment]
Took a look through https://docs.mattermost.com/administration/data-retention.html and I think @wiersgallak's comments would be useful in the doc as FAQs. 

FAQ 1: How long does it take to run a deletion query and does it affect server performance?
FAQ 2: How do I know whether the data retention job is running/scheduled? 

Let me know what you think.

**Comment by justinegeffen** [comment]
Closing as the initial request is complete. A new issue has been opened for the potential new FAQs.
