### ISSUE TITLE
Request for Documentation: Document process for creating a new autolink in community.mattermost.com

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#3442]
Mattermost user `jason.blais` from https://community-release.mattermost.com has requested the following be documented:

```
Steps are:
1. Define the word and URL to autolink to (e.g. "ISP" to https://handbook.mattermost.com/operations/operations/issue-solution)
2. Message @jesse.hallam in ~ask-r-and-d to help add the new auto-link

To learn more about autolink plugin, see https://github.com/mattermost/mattermost-plugin-autolink
```

See the original post [here](https://community-release.mattermost.com/_redirect/pl/c7eyg5qht3b1jjtpczygf6rxah).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by jasonblais** [comment]
@justinegeffen This should go to the handbook repository (I selected "Company Handbook" as the option in Doc Up plugin)

Can you help ask Joram to update the autolink plugin on community.mattermost.com, so that issues marked for "Company Handbook" are created in https://github.com/mattermost/mattermost-handbook/issues?

**Comment by justinegeffen** [comment]
Done. :) https://github.com/mattermost/mattermost-handbook/issues/84.
