### ISSUE TITLE
[Help Wanted] Limit sidebar to show a maximum of three levels of nesting.

### ISSUE THREAD

**Issue by esethna** [mattermost/docs#370]
Observed: The sidebar will expand to as many levels of heading as are in the document. See screenshot #1.
![image](https://cloud.githubusercontent.com/assets/14333569/17711153/855701ba-63ad-11e6-97f6-bc55112e5146.png)

Expected: The sidebar is limited to expanding to three nested levels of headings. For the above example, the maximum expansion of the sidebar would be:

![image](https://cloud.githubusercontent.com/assets/14333569/17711251/ef0ffd6e-63ad-11e6-9c26-ebb050e1d3ea.png)

**Comment by it33** [comment]
@esethna wondering why L3 and not L4? 

Seems like there's some chapters with very long sections and headings in the LHS would help navigate. 

I agree the L4 headings don't look very nice right now, wondering if instead we should ask @asaadmahmood's help to format those better, rather than remove L4?

![image](https://cloud.githubusercontent.com/assets/177788/17712716/1248dc26-63ac-11e6-8ebf-0d2ca802e7cf.png)

**Comment by esethna** [comment]
I will queue for UX meeting and circle back after chatting with Asaad. Thanks!

**Comment by esethna** [comment]
Ticket created [here](https://mattermost.atlassian.net/browse/PLT-3974) for Asaad to look at improvements to the formatting of sidebar on docs. Closing this ticket.
