### ISSUE TITLE
Request for Documentation: add some notes or forum post about saml idp with okta

### ISSUE THREAD

**Issue by matterdoc** [mattermost/docs#4086]
Mattermost user `sven.huester` from https://community-daily.mattermost.com has requested the following be documented:

```
Maybe we can add something like best practices when using saml with okta.
For example this is very important:

> For SAML they use `user.id` as the ID attribute value mapping. In LDAP they use `uniqueIdentifier`

```

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by cwarnermm** [comment]
@svelle - Is it possible to get a bit more context around this documentation request, please? Is there a conversation or a Support ticket that led to this request being logged? I'm looking for more detail around the problem being faced and how best to address it via product documentation. Thanks for your help with this!

**Comment by svelle** [comment]
Hey @cwarnermm so this note did indeed come from a customer conversation. Not a ticket though, otherwise I would've linked it here, sorry.

Basically the problem that the customer had was that when using Okta as their SAML idp they didn't use the `user.id` as the Mattermost User ID attribute, wheras in Okta's LDAP you'd use `uniqueIdentifier`. 

Does that make more sense to you now?

**Comment by cwarnermm** [comment]
Thanks so much @svelle! This context helps!
