### ISSUE TITLE
Configuration settings for "Email" don't seem to be organized under the right headings

### ISSUE THREAD

**Issue by sadohert** [mattermost/docs#4138]
Starting from this top-level documentation page:

https://docs.mattermost.com/administration/config-settings.html

If I click on the "Email" entry of the table of contents I'm take down to the "Experimental Settings on in config.json", which seems to be blank, so not required.

I was actually trying to get to the "Email Notifications/Server" settings section [here](https://docs.mattermost.com/administration/config-settings.html#smtp).

Granted, if had been paying attention to the Primary Section I was clicking in I would have known it was for "Experimental" settings, but my journey to SMTP would be a bit longer than it should be.

Wondering if we:
1.  Remove the "Experimental Settings" section which doesn't seem to have anythign in it anyway
2. Add to the SMTP header to say "SMTP (Email Notifications)"

**Comment by sadohert** [comment]
Actualy, the stuff I was looking for was in the notifications section:

https://docs.mattermost.com/administration/config-settings.html#enable-email-batching

Given a bunch of these settings are organized under the same section of `config.json` I wonder if they should be discoverable on the docs page this way.

**Comment by justinegeffen** [comment]
Thanks for this, @sadohert. I've assigned @cwarnermm to this for her perspective. :)

**Comment by cwarnermm** [comment]
@sadohert cc @justinegeffen 
The organization of Mattermost Server configuration settings is not an ideal self-serve experience for users. I agree with @sadohert that reducing path friction and making content more discoverable is a key goal.

Organizing the configuration settings in a customer-focused, logical, discoverable way is likely a bigger cross-team discussion.

Immediate recommendations: apply #1 & #2 and confirm #3 below:

1. [SMTP](https://docs.mattermost.com/administration/config-settings.html#smtp)
- update title to "SMTP Email Server"
- update description as "Location of SMTP email server used for email notifications."

2. [Enable Email Batching](https://docs.mattermost.com/administration/config-settings.html#enable-email-batching)
- update the note to include a link to the updated SMPT section since SMTP is also required for email notifications/email batching.

Review the Experimental section and confirm whether current content is intentional or requires updates:

3. [Experimental](https://docs.mattermost.com/administration/config-settings.html#experimental)
- Features = appears empty; intentional?
- AD/LDAP Settings = appears empty; intentional?
- Inconsistent use of (Experimental) in titles - intentional?

Thoughts? Concerns?

**Comment by justinegeffen** [comment]
Thanks, @cwarnermm! I'm 5/5 on all your suggestions. 

Wrt point 3, I think the issue is actually with the header formatting and that it is possibly meant to be H1: Experimental > H2: Features > H3 AD/LDAP Settings followed by the content. I am not certain this is the case though, so looping @wiersgallak in as she may have a better idea. 

<img width="1159" alt="Screen Shot 2020-12-03 at 09 32 46" src="https://user-images.githubusercontent.com/4223530/100978290-ddcd3f80-354a-11eb-99ea-7436da8a6f42.png">
