### ISSUE TITLE
Update docs for saved messages

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/docs#4257]
Flagged messages are now saved messages but docs were not updated: https://docs.mattermost.com/help/messaging/flagging-messages.html

![image](https://user-images.githubusercontent.com/1192780/105417877-1905f980-5bf1-11eb-9375-0f5a71f95d3d.png)

**Comment by haardikdharma10** [comment]
@cwarnermm, Mind if I work on this issue? Would be a great opportunity for me to improve the docs:)

**Comment by cwarnermm** [comment]
Hi @haardikdharma10 - I love your enthusiasm and your interest in making Mattermost product documentation better for everyone. I'd like to keep this ticket with me because I'm in the process of updating these sections of the User Guide documentation to include all the great new sidebar functionality that's coming in an upcoming release. Once that content is released, I welcome your feedback! Thank you again for all of your Mattermost contributions -- you're doing great work that everyone can benefit from.

**Comment by cwarnermm** [comment]
Documentation updated via: https://github.com/mattermost/docs/pull/4298
