### ISSUE TITLE
What GitLab scopes are actually required

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/docs#4611]
https://docs.mattermost.com/deployment/sso-gitlab.html says to leave scopes unchecked. It's desirable to not allow all scopes - which are actually required?

Related to https://github.com/mattermost/docs/issues/4034 & https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/6165

**Comment by bbodenmiller** [comment]
@hmhealey any inputs?

**Comment by hmhealey** [comment]
I'm not sure actually. I haven't worked with the OAuth code much myself, so I'm not familiar with setting it up. Does Omnibus perhaps set some scopes when autoconfiguring Mattermost?

**Comment by justinegeffen** [comment]
I think @jasonblais may be a good resource for this question or can refer you to the right person. Thanks, @bbodenmiller!

**Comment by jasonblais** [comment]
@bbodenmiller Is this a new requirement by GitLab to require at least one scope? Previously I just left the scopes blank / didn't select any scopes, and it worked.

**Comment by hmhealey** [comment]
Ideally, I think we would specify some scopes for this so that we're limiting the amount of information that's made available to Mattermost from GitLab, but I'm not certain how much we'd need for that. It might just be whatever scope gives us access to the user's name and email since I don't know what else we pull for GitLab-connected accounts.

**Comment by jasonblais** [comment]
> Ideally, I think we would specify some scopes for this so that we're limiting the amount of information that's made available to Mattermost from GitLab, but I'm not certain how much we'd need for that. It might just be whatever scope gives us access to the user's name and email since I don't know what else we pull for GitLab-connected accounts.

@wiersgallak This feels like it would involve PM to investigate and come with a recommendation. I wonder if this is something that would fall under Aaron's ownership?

**Comment by wiersgallak** [comment]
@aaronrothschild Can you please assist with looking into this further?

**Comment by aaronrothschild** [comment]
@mkraft do you know where I might start looking into this?  It seems like I need to find out what is the minimum scopes required for our OAuth OpenId integration with Gitlab to function properly.  From reading https://docs.gitlab.com/ee/administration/auth/oidc.html I'm unsure if the issue is we need to send something like `send_scope_to_token_endpoint` as `false` (instead of default true). OR maybe we just need to specify `'openid','profile'` as the minimum required.

**Comment by cwarnermm** [comment]
Documented via https://github.com/mattermost/docs/pull/5317

**Comment by cwarnermm** [comment]
Documented via https://github.com/mattermost/docs/pull/5317

**Comment by bbodenmiller** [comment]
Unfortunately this is still lacking for Team Edition - System Console > Authentication > OpenID Connect does not exist as instructions says to use.

And regarding following on https://docs.mattermost.com/onboard/sso-gitlab.html

> Update the config.json file to specify the scopes selected for the GitLabSettings property. At a minimum, openid is a required scope for the connector to work. Changes to this setting require a server restart before taking effect.

What format is one supposed to use? Why does this guidance not match the scopes in instructions above on page?

**Comment by jasonblais** [comment]
cc @cwarnermm on above
