### ISSUE TITLE
Add CLI doc updates for GitLab

### ISSUE THREAD

**Issue by amyblais** [mattermost/docs#5285]
These 2 docs need updates:

1. https://docs.mattermost.com/manage/command-line-tools.html#use-the-cli-on-gitlab-omnibus
2. https://docs.gitlab.com/ee/integration/mattermost/#mattermost-command-line-tools-cli (I'm not sure who normally owns updating this ... so let me know any concerns!)

More context here: https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/6490#note_745347313.

Let me know any questions!

**Comment by nab-77** [comment]
@justinegeffen @cwarnermm how can I help move this forward. The deadline for GitLab 14.6 (where MM 6.1 is going to be included) is drawing close.

**Comment by cwarnermm** [comment]
Thanks, @nab-77! A deadline for this one wasn't clear, so I appreciate knowing the urgency on this one. I'll review today and follow up with you about any gaps or information I need assistance with to complete these doc updates by end of day.

**Comment by nab-77** [comment]
Please let me know how I can help.

**Comment by decrementor** [comment]
Using the GitLab OAuth2 integration with Mattermost: No formal documentation specifies how to use `mmctl auth login --strict URL --name HOST --access-token STRING` properly. Which token? From where? I found a help written for developers using the API with some guidance on how to acquire a Mattermost token. Sadly, Mattermost session tokens are not able to be created from within Mattermost because the GitLab integration appears to disable the "Manage Tokens" features completely--- even for Super Attempting to use an Auth Token from within GitLab fails as does using a web-browser session token. Basically, without the `mattermost` command, based on the scant information available and scanning the source code, it appears to me right now that `mmctl` cannot even be used against GitLab + Mattermost installations? This issue is likely MUCH more urgent than just for the upcoming GitLab release.
