### ISSUE TITLE
Help Wanted: Clarify Audit Logging Configuration Placement

### ISSUE THREAD

**Issue by icelander** [mattermost/docs#5407]
In the Audit Log v2 docs under [Configuring Audit Log in Mattermost](https://docs.mattermost.com/comply/audit-log.html#configure-audit-log-in-mattermost) it says this:

> Open config.json and navigate to the audit settings under ExperimentalAuditSettings. Within the setting AdvancedLoggingConfig you are able to specifiy a filespec to another config file, a database DSN, or JSON.

However, it does not provide an example of what this looks like in the `config.json`, nor a reference to describe what a `filespec` means.

**Comment by untergeek** [comment]
I'm with @icelander here. I've tried and all I can get is errors:

```
Mar 16 17:53:33 mattermost mattermost[117406]: Error: failed to load configuration: failed to create store: unable to load on store creation: parsing error at line 167, character 35: json: cannot unmarshal object into Go struct field ExperimentalAuditSettings.ExperimentalAuditSettings.AdvancedLoggingConfig of type string
```

And that comes from this:

```
        "AdvancedLoggingConfig": {
          "file_1": {
              "Type": "file",
              "Format": "json",
              "Levels": [
                {"ID": 100, "Name": "audit-api"},
                {"ID": 101, "Name": "audit-content"},
                {"ID": 102, "Name": "audit-permissions"},
                {"ID": 103, "Name": "audit-cli"}
              ],
              "Options": {
                  "Compress": true,
                  "Filename": "audit.log",
                  "MaxAgeDays": 1,
                  "MaxBackups": 7,
                  "MaxSizeMB": 500
              },
              "MaxQueueSize": 1000
          }
        }
```

**Comment by Gregesp** [comment]
Hello,

I try to use this parameter also for the LoggingSettings and NotificationLogSettings, it doesn't work for me also.

I put a JSON file with relative path, absolute path or else a Nested/Embedded JSON in the configuration file and i have this error or 2 others errors. I've try to use brackets [ ] and double quotes " " or not with the Embedded JSON with no sucess, i minified the nested JSON on a single line and it doesn't work also.

I can see on the documentation 2 formats of JSON, i try also this 2 formats and it doesn't work too.
-> https://docs.mattermost.com/_downloads/b7017a864f9dd114c67f6dc381621c4f/sample-logger-config.json
-> https://docs.mattermost.com/_downloads/c4100cd437d430795506d20eee0a068f/advanced-logging-options-sample-json.zip

I don't used the syntax of the text file config here -> https://github.com/mattermost/docs/files/5066579/Log.Settings.Options.txt

I will post my others errors messages.

In my case, i use a centralized configuration in database because we using High Availability and SAML features (my certificates and key are not loaded on database)

**Comment by cwarnermm** [comment]
@wiggin77 - Would you be able to assist with this issue, please?

**Comment by wiggin77** [comment]
> n my case, i use a centralized configuration in database 

@Gregesp I know the docs don't (yet) make this clear, but when the main config is stored in the database then the auxiliary files also need to be in the database.  So your AdvancedLoggingConfig files would have to be added to the database via `mmctl`.  Someone did this recently and I'm trying to find the example command line for adding these files via mmctl.

**Comment by Gregesp** [comment]
> > n my case, i use a centralized configuration in database
> 
> @Gregesp I know the docs don't (yet) make this clear, but when the main config is stored in the database then the auxiliary files also need to be in the database. So your AdvancedLoggingConfig files would have to be added to the database via `mmctl`. Someone did this recently and I'm trying to find the example command line for adding these files via mmctl.

Hello,
I tried to import JSON file on database with the CLI `mattermost import`, but it doesn't work. I tried also a formatted JSON file and it doesn't work.
I dont use `mmctl import upload` or others commands because i try to automate the deployment and as mattermost doesn't have an admin account builtin i can't use this CLI, to use it i think i do firstly create the account who will be affected with the System Admin Role.

**Comment by icelander** [comment]
@Gregesp I was able to get the audit logging to work with configuration in database like this:

First, put the audit logging settings into a JSON file, e.g. `audit_logging.json`

Next, run this command to use  set a shell variable to the escaped JSON using `jq`

```bash
config=`jq -c '.' < ./audit_logging.json` 
```

Then, run this command to set the configuration value:

```bash
mmctl config set ExperimentalAuditSettings.AdvancedLoggingConfig $config
```

If you are trying to automate deployment, you can use `mmctl --local` and enable [Local Mode](https://docs.mattermost.com/configure/configuration-settings.html#enable-local-mode)

**Comment by icelander** [comment]
Other improvements to add:

 - List the available log levels and what events are included
 - Indicate which log levels should go in `ExperimentalSettings.AdvancedLoggingConfig` and which should be in `LogSettings.AdvancedLoggingConfig`
 - Add a note about having to restart when changes are made
 - Also note that if you use a JSON object in the config file it must be escaped
 - Provide more example configurations and an explanation of what they all log

**Comment by cwarnermm** [comment]
Thanks, @TomerPacific! This is an older ticket that doesn't need further updates and can be closed. I appreciate you bringing these to my attention!
