### ISSUE TITLE
[Help wanted] Fix search for "Upgrade"

### ISSUE THREAD

**Issue by it33** [mattermost/docs#583]
Search for "Upgrade" and upgrade page doesn't appear. Need to find out why, and later write out some criteria so it is easier to find regressions in search

**Comment by anchepiece** [comment]
There seems to be a lot of issues with searching. Results are unsorted, seem to miss searching titles, missing entries that clearly include the search term (like the above "upgrade").

Since docs are built on the sphinx_rtd_theme theme I'll take a look there and see if there is anything obvious, but a quick snoop on the "upgrade" term clearly has matching results in the generated index.

**Comment by jasonblais** [comment]
Fixed by #745, thanks @shieldsjared!!
