### ISSUE TITLE
New documentation page for JumpCloud SAML integration

### ISSUE THREAD

**Issue by azigler** [mattermost/docs#6549]
Hi @cwarnermm! @jlandells produced a great "Mattermost-JumpCloud Integration: A Step-by-Step Guide to SAML Authentication" video that will be going live on our YouTube channel later this week. To correspond with the instructional video, we also want to have documentation. Both of the resources should backlink to each other, so the same info is available in two different learning styles.

John produced a draft of the documentation [here](https://docs.google.com/document/d/1PyS7FVS6uPCczVfAbXOzNJ4qauLdg4NkLK1D9YYwMh8) and his thought is that somewhere on [the SAML section of this page](https://github.com/mattermost/docs/blob/master/source/configure/authentication-configuration-settings.rst#saml-20) should be the link to this new page.

Could we tag your help with getting the page staged up? It doesn't need to go live the same time as the video, but we'd like to get it up not long after. Let us know what questions you may have!

**Comment by cwarnermm** [comment]
Thanks, @azigler! We'll be publishing this information as a Mattermost Discussion Forum post rather than a product documentation update due to the fact that this integration isn't necessarily something we're equipped to support internally at this time in an official capacity.

Please share the final YouTube URL and I'll be happy to include a link to it in the forum post. Thanks!

**Comment by azigler** [comment]
Thanks @cwarnermm! cc @jlandells

**Comment by cwarnermm** [comment]
JumpCloud integration documentation is now available on the Mattermost User Forum: https://forum.mattermost.com/t/does-mattermost-integrate-with-jumpcloud-for-saml-authentication/16572

**Comment by azigler** [comment]
Thanks y'all! I'll get this added to the resource card and YouTube video.
