### ISSUE TITLE
[Help Wanted] Error when searching for "Reply" in docs.mattermost.com

### ISSUE THREAD

**Issue by it33** [mattermost/docs#718]
Repro: 

1. Search for "Reply" on docs.mattermost.com

Observed: 

1. System freezes and JS error seen in console. Does not happen when you search for "Fish" 

![image](https://cloud.githubusercontent.com/assets/177788/20991607/4282062e-bc94-11e6-8add-e8ab635b2a28.png)

**Comment by shieldsjared** [comment]
@it33 - It looks like sphinx has a LOT of [open issues](https://github.com/sphinx-doc/sphinx/issues), many of which contain the keyword ["Search"](https://github.com/sphinx-doc/sphinx/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20search)... which is mildly concerning.  It might be time to consider integrating a tool specific for document indexing/searching in order to increase the utility of the search.  Sphinx has the ability to create an adapter as an external search provider.  Thoughts?  I'm happy to look into this route if your open to it.

**Comment by shieldsjared** [comment]
Although version 1.5 of sphinxdoc was just released and the changlog references correcting incomplete search results. Have y'all updated the build server to v1.5? I'm not at a computer at the moment to test it myself.

**Comment by it33** [comment]
Thanks @shieldsjared, highly appreciate your analysis, I'd defer to @coreyhulen on the upgrade to Sphinx 1.5 and new search provider. 

In my mind, so long as we test it before hand, I imagine it would be fine for generating static output,

**Comment by coreyhulen** [comment]
I have no objections to upgrading to the latest.

**Comment by shieldsjared** [comment]
@it33 @jasonblais - I think this can be closed.  Resolved with #745.

**Comment by jasonblais** [comment]
Thanks @shieldsjared!
