### ISSUE TITLE
Update style guides documentation

### ISSUE THREAD

**Issue by jasonblais** [mattermost/docs#772]
1) Add user account and parameter formatting to documentation style guides

From discussion with @JeffSchering  https://github.com/mattermost/docs/pull/742#issuecomment-271437911

**Comment by JeffSchering** [comment]
# Style Guide updates

This is a raw, unedited, rough, unofficial list of updates proposed for the style guide. Comments and suggestions welcome!

## Text highlighting

Additions to this table: https://docs.mattermost.com/process/mattermost-doc-style.html#text-highlighting

- italicize names of user accounts Eg. Log into the *postgres* account.
- italicize variable names
- italicize param names in config files when referring to them in the text (not in the file example itself)
- monospace param values in config files when referring to them in the text (not in the file example itself)

## Placeholders for user-specific names

- add use of {} around place holders. For eg, "--nginx -d *{domain-name}* && sudo service nginx reload``

## word list
- login vs log in vs log-in
- log in to not log into
- setup vs set up
- sign in vs sign-in

## Note about when to apply styleguide:
  - when creating a new doc
  - when converting a doc from .md to .rst
  - when revising a doc, apply styleguide to the part that you changed, unless it would be jarringly inconsistent with the rest of the doc. In that case, if you have time to update the rest of the doc, then do so, otherwise use a style that best fits with the existing doc and create an issue in GitHub to fix the style (perhaps a Help Wanted?)

If updating the style will impact a release or if the scope is significantly greater than originally planned for, then do what you can and what makes sense, and then create an issue in GitHub. For example,  "File XXX converted to .rst, but does not meet requirements of the Style Guide."

## Titles in top-level parent docs

The title in a top-level parent doc should have both title underline and title overline. The reason for this is so that the Sphinx processor creates the correct hierarchical structure in the ToC.

Parent docs have one or more include statements. Top-level parent docs, in addition to the include statements, are at the root of the hierarchy for that particular topic. For example, source\install\install-ubuntu-1404.rst is a top-level parent doc.

## Other

- Review comments still outstanding in https://github.com/mattermost/docs/pull/642

- Update underline specs. See https://pre-release.mattermost.com/core/pl/oo5k3en8wtf87jgd5taux67a4w

- How to handle menu selections. For example:

        System statistics are viewable under **System Console > Reporting > Site Statistics**.

    instead of

        System statistics are viewable under **System Console** > **Reporting** > **Site Statistics**.

**Comment by JeffSchering** [comment]
Waiting for PR https://github.com/mattermost/docs/pull/793 to get merged, then I'll start working on this.

**Comment by JeffSchering** [comment]
Closing. Implemented in PR https://github.com/mattermost/docs/pull/865
