### ISSUE TITLE
Document APR/Help Wanted process

### ISSUE THREAD

**Issue by it33** [mattermost/docs#806]
Opening ticket to discuss APR/Help Wanted goal, principles and plan 

For the plan part: 

1. What's required for a Help Wanted / APR ticket? 
2. When to use Jira vs GitHub?
3. What's the process to review, refine and execute on tickets?

**Comment by jasonblais** [comment]
Thanks @it33! Below you can find some thoughts from my end.

Some of it is based on https://github.com/mattermost/docs/pull/737 which is a PR for community guidelines I submitted before holidays and includes a proposed process for help wanted issues. It's WIP and needs some cleaning up to do, particularly to simplify the help wanted issue creation process a bit.

----

Proposed goals and principles:

**Goal**: Increase Mattermost usage through larger and more numerous deployments via a vibrant open source community that contributes features that would not otherwise be offered.

**Principles**:
 - Contributors get a worthwhile benefit from their contributions, from the feature directly and/or from social recognition
 - Community members should have a low barrier to contribute
 - Community development workflow should be clear, efficient and effective

^I added the third principle from your suggestion, which I thought suits well here.

----

Questions: 

1 - What's required for a Help Wanted / APR ticket?

Here's a visual summary of what's included in PR #737

![image](https://cloud.githubusercontent.com/assets/13119842/22187613/9d246074-e0d7-11e6-921f-9dc7676b28d7.png)

2 - When to use Jira vs GitHub?

By default, we should use Jira for both Mattermost and community tickets, with community tickets moved over to Help Wanted issues. 

Benefits:
 - anyone can create Jira tickets as they are prioritized by triage - but it's not clear who can create help wanted issues and in turn decide that they're low priority (clear)
 - Jira tickets can be more easily referred back to and searched for as they're in one place (clear, effective)
    - *A customer who wants to search for open issues only has to search one place and can use customer-labelled Jira queries*
 - all Jira tickets get automatically triaged, prioritized and approved by a dev and a PM (efficient) 
 - Zapier integration can be made which automatically creates GitHub help wanted issues from APR-labelled Jira tickets, requiring 0 mana (efficient)
 - re-prioritizing tickets is easy, as they're all in JIRA --> you can easily move issues up and down sprints as needed and turn tickets into APRs. (efficient)
    - *Otherwise, we'd have to keep moving tickets between the two sites if they become important or conversely get de-prioritized*
 - resolved Jira tickets are automatically assigned to a QA, who tests them on the CI (efficient, effective) 
    - *No such process in GitHub*
 - fits an already-proven workflow where community Help Wanted issues simply become integrated to it (effective)
![image](https://cloud.githubusercontent.com/assets/13119842/22193768/b6ba0d52-e10b-11e6-9cbe-4cbe655fc895.png)
    - *if we completely separated Jira tickets and GitHub issues, we'd need to have someone managing both processes separately*
![image](https://cloud.githubusercontent.com/assets/13119842/22193773/bd854e1c-e10b-11e6-982d-8a3ccff989d2.png)

**Exceptions:** There are exceptions to the rule. For instance dev driven unit tests that the core team doesn't have time for doesn't need to be in Jira as it's something that customers wouldn't search for or a QA be testing for.

3 - What's the process to review, refine and execute on tickets?

This is in progress in #737. See proposals for [managing help wanted issues](https://github.com/mattermost/docs/blob/a0897a3e177f0f6f1a7aab2285e0e2d2cba36b0a/source/process/community-guidelines.rst#managing-help-wanted-issues) and for [closing them](https://github.com/mattermost/docs/blob/a0897a3e177f0f6f1a7aab2285e0e2d2cba36b0a/source/process/community-guidelines.rst#closing-help-wanted-issues).

**Comment by jasonblais** [comment]
Addressed by #823
