### ISSUE TITLE
[Help Wanted] Change "View page source" link to "Edit" link to GitHub page

### ISSUE THREAD

**Issue by it33** [mattermost/docs#86]
Would appreciate help from anyone who can make a PR to change the "View page source" link to an "Edit" link to GitHub page to make it easier for community members to contribute changes. 

![image](https://cloud.githubusercontent.com/assets/177788/14224561/6fd744c6-f855-11e5-9e1b-58589bca015f.png)

**Comment by awicket** [comment]
Hi.

In `source/conf.py` you can disabled the option, change `#html_show_sourcelink = True` for `html_show_sourcelink = False` and make your html again.

There option create a `build/html/_sources` with your docs in .txt. This is a option from sphinx, and you need custom version to change from create a dir `_sources` to link a your specific file in your repo.

With `html_show_sourcelink = False`

![captura de pantalla 2016-05-08 a las 17 19 16](https://cloud.githubusercontent.com/assets/3390298/15098634/b18adf96-1541-11e6-8b6d-be4555c99f76.png)

**Comment by it33** [comment]
Thanks @awicket! @DavidLu1997 for next week, could we have your help seeing if you can figure out a PR to enable this?

**Comment by it33** [comment]
Hi @ajerezr, just saw your other pull request, would you be interested in making a PR for this change? 

You seem knowledgable, the community could really use your help,

**Comment by ajerezr** [comment]
@it33 There is https://github.com/mattermost/docs/pull/150

**Comment by shieldsjared** [comment]
According to the documentation and the source for the sphinx_rtd_theme, you _should_ be able to put a `.. meta::` flag, and define `:github_url` for each file... However, when I tried doing this, the meta class was always empty and it had no impact on the URL (it did, however, add the url as an actual meta directive in the HTML file).  Take a look the [breadcrumb's source code](https://github.com/snide/sphinx_rtd_theme/blob/rc-0.1.9/sphinx_rtd_theme/breadcrumbs.html) to see what I'm referring to.

As an alternative, you can generate your own `breadcrumbs.html` template to override the one provided by the theme.  All you need to do is create a `breadcrumbs.html` file in the templates directory, with the content as such
````html
<div role="navigation" aria-label="breadcrumbs navigation">
  <ul class="wy-breadcrumbs">
    {% block breadcrumbs %}
      <li><a href="{{ pathto(master_doc) }}">Docs</a> &raquo;</li>
        {% for doc in parents %}
          <li><a href="{{ doc.link|e }}">{{ doc.title }}</a> &raquo;</li>
        {% endfor %}
      <li>{{ title }}</li>
    {% endblock %}
    {% block breadcrumbs_aside %}
      <li class="wy-breadcrumbs-aside">
        {% if pagename != "search" %}
          <a href="https://github.com/mattermost/docs/blob/master/source/{{ conf_py_path }}{{ pagename }}{{ suffix }}"  class="fa fa-github"> Edit on GitHub</a>
        {% endif %}
      </li>
    {% endblock %}
  </ul>
  <hr/>
</div>
````

Let me know if this is an acceptable, and ill submit a PR.  I'm not the biggest fan of it because I hate have to completely override things for something so trivial... but it's the only way I was able to get it to work with < 2 hours of experience with Sphinx and RST syntax.

![githublink_screenshot](https://cloud.githubusercontent.com/assets/600643/17458508/374316a8-5bd8-11e6-897a-abd051af450f.png)

**Comment by shieldsjared** [comment]
Apologize for the crazy history above... Submitted PR #346 to resolve this issue.

**Comment by it33** [comment]
Thanks @shieldsjared, closing as solved!
