### ISSUE TITLE
Draft improved process for security issue numbering

### ISSUE THREAD

**Issue by lfbrock** [mattermost/docs#871]
The old security issue numbering system on https://about.mattermost.com/security-updates/ does not make much sense. 

(The security issues were numbered by version, with a number appended to the end to count the num - eg Security Issue v3.6.0.1 would be the first security issue added to the v3.6.0 release. This was confusing though, as v3.6.0.1 sounds like a version number). 

This ticket is to come up with a better numbering process, and document it.

**Comment by lfbrock** [comment]
Lindy started a draft for this, we just need it reviewed and finalized.

**Comment by justinegeffen** [comment]
@DSchalla, I've looked at this page: https://mattermost.com/security-updates/ and it looks like the "fix version" refers to the Mattermost version in which the fix was included? We also have this page which I feel explains it well: https://handbook.mattermost.com/operations/research-and-development/product/release-process/security-release. 

Would you be comfortable with this issue being closed?
