### ISSUE TITLE
Create a doc that explains how the rate limiting settings affect the Mattermost instance

### ISSUE THREAD

**Issue by jasonblais** [mattermost/docs#894]
Original Jira ticket here: https://mattermost.atlassian.net/browse/PLT-4406

Corey and Chris can help with technical details

**Comment by mirhonda** [comment]
👋 @jasonblais and @lfbrock: I look forward to addressing this my work simulation. Please confirm the accuracy of my audience analysis to inform my content strategy.
* _audience: Who are we writing the topic for?_ 
Admins and end users
* _version(s): Does the situation apply to previous releases, for the current release and going forward, or a future release?_
The information need is a combination of conceptual and procedural content. The conceptual information about ways that rate limit settings affect a Mattermost instance and guidelines for recommended values are appropriate for all versions. Procedures or methods for rate limiting by IP address and user authentication token should be written generically so that users can follow instructions across any version.
* platforms: Does this situation apply to every platform or only specific one(s)?
The content applies to all platforms.
* related topics: Are there other existing topics that the reader should consider? Do parallel or other topics need to be written? I envision this as a total of four topics - two conceptual and two procedural; with one set (concept and procedure) in the User's Guide and a second set in the Admin's Guide.

**Comment by mirhonda** [comment]
Thanks for answering my questions in our channel @jasonblais and @lfbrock. Here is the content strategy for the new topic:
### Summary
New topic that provides an overview of rate limiting. This topic will be a combination of conceptual and procedural content to support administrators in setting rate limits as it relates to Mattermost.
### New content
Topic title: “Setting Rate Limits“
* Explain what a rate limit is
* Explain implications and benefits of rate limit settings to a Mattermost instance
* Provide three (basic, intermediate, and advanced or low, medium and high) scenarios and recommended rate limit values for each one
* Explain rate limiting methods
    * Limit by IP address
    * Limit by User Auth token
### Outstanding questions
* Should we mention that users need admin credentials or is that a given?
* Warn against any particular actions?

**Comment by jasonblais** [comment]
Great, thanks @mirhonda! 

> Should we mention that users need admin credentials or is that a given?

We'll include it in the Admin's guide so we can take Mattermost admin credentials as given.

> Warn against any particular actions?

If there's something admins should be aware of before taking some actions, that would be helpful to include.

**Comment by justinegeffen** [comment]
We have a section on rate limiting in the config guide: https://docs.mattermost.com/configure/configuration-settings.html#rate-limiting. Would you say that covers this request?

**Comment by jasonblais** [comment]
@justinegeffen It would be good to have a one-pager of what are the implications of changing the rate limit settings. E.g. something what's described in https://github.com/mattermost/docs/issues/894#issuecomment-380805387

**Comment by cwarnermm** [comment]
Replaced by https://github.com/mattermost/docs/issues/6591
